add support for sideloading addons via the addon manager or file picker
fork-maintainers/iceraven-browser pull request #702
Opened 2023-11-28 20:04 UTC by GamerGirlandCo

> if you want something done right, you'll always have to do it yourself...

closes #31

2023-11-28 20:05 UTC, GamerGirlandCo commented
closes #158 #438 #31

2023-11-29 12:14 UTC, akliuxingyuan commented on app/src/forkRelease/res/menu/addons_menu.xml
> +		<item
fix indentation

2023-11-29 12:18 UTC, akliuxingyuan requested changes

2023-11-29 12:18 UTC, akliuxingyuan commented on app/src/forkRelease/res/menu/addons_menu.xml
> +		<item
fix indentation

2023-11-29 12:18 UTC, akliuxingyuan commented on app/src/main/AndroidManifest.xml
> -
add this line back? changes like this may add extra effort to merge upstream changes

2023-11-29 12:18 UTC, akliuxingyuan commented on app/src/main/AndroidManifest.xml
> +                <data android:mimeType="*/*"/>
we can restrict it to application/x-xpinstall

2023-11-29 12:18 UTC, akliuxingyuan commented on app/src/main/AndroidManifest.xml
> +
remove useless spaces

2023-11-29 12:18 UTC, akliuxingyuan commented on app/src/main/java/org/mozilla/fenix/addons/AddonInstallIntentProcessor.kt
better to convert tabs in this file to spaces

2023-11-29 12:18 UTC, akliuxingyuan commented on app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
> +            .setType("*/*")
we can restrict it to application/x-xpinstall

2023-11-29 12:18 UTC, akliuxingyuan commented on app/src/main/java/org/mozilla/fenix/components/IntentProcessorType.kt
> +
same above

2023-11-29 12:18 UTC, akliuxingyuan commented on app/src/main/res/values/ids.xml
we don't need this file

2023-11-29 12:26 UTC, akliuxingyuan commented
Thank you making this Pull Request, it's very helpful!!
I test it locally and it works gracefully, but I notice that after add-on installed successfully, the installed add-on list doesn't get a refresh, can you make it better?

2023-11-30 08:29 UTC, 255doesnotexist commented
awesome works

2023-11-30 12:59 UTC, merged

2023-12-01 13:01 UTC, alexolog commented
Does it support auto-updates?

2023-12-02 13:11 UTC, VillagerTom commented
Xpi file can't be selected in DocumentsUI.

2023-12-26 03:26 UTC, NightshadeGS commented
addon file greyed out and not selectable in file selection dialogue.